apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    category: {{category}}
spec:
  type: NodePort
  selector:
    category: pwn
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30001
