{{#if namespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{namespace}}
---
{{/if}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
  {{#if namespace}}
  namespace: {{namespace}}
  {{/if}}
  labels:
    category: {{category}}
    challenge: {{name}}
spec:
  {{#if replicas }}
  replicas: {{replicas}}
  {{else}}
  replicas: 1
  {{/if}}
  selector:
    matchLabels:
      category: {{category}}
      challenge: {{name}}
  template:
    metadata:
      labels:
        category: {{category}}
        challenge: {{name}}
    {{#if containers}}
    spec:
      containers:
      {{#each containers}}
      - name: {{@key}}
        image: {{image}}
        {{#if resources}}
        resources:
          {{#if resources.limits}}
          limits:
            cpu: {{resources.limits.cpu}}
            memory: {{resources.limits.memory}}
          {{/if}}
          {{#if resources.requests}}
          requests:
            cpu: {{resources.requests.cpu}}
            memory: {{resources.requests.memory}}
          {{/if}}
        {{/if}}
        {{#if ports}}
        ports:
        {{#each ports}}
        - containerPort: {{containerPort}}
          name: port-{{containerPort}}
        {{/each}}
        {{/if}}
      {{/each}}
  {{/if}}

{{#if expose}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  {{#if namespace}}
  namespace: {{namespace}}
  {{/if}}
  labels:
    category: {{category}}
    challenge: {{name}}
spec:
  type: NodePort
  selector:
    category: {{category}}
    challenge: {{name}}
  ports:
    {{#each expose}}
    - port: {{containerPort}}
      name: port-{{containerPort}}
      targetPort: {{targetPort}}
      nodePort: {{nodePort}}
    {{/each}}
{{/if}}
