on:
  push:
    branches:
      - master
    tags:
      - "v*"

name: Github Release ctfup

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: git fetch --all --tags

      - name: Check version change
        uses: thebongy/version-check@v1
        id: check
        with:
          file: package.json
          failBuild: false
          tagFormat: v${version}

      - name: Echo variables
        run: |
          echo "versionChanged- ${{steps.check.outputs.versionChanged}}"
          echo "releaseVersion- ${{steps.check.outputs.releaseVersion}}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.check.outputs.versionChanged == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.releaseVersion }}
          release_name: Release ${{ steps.check.outputs.releaseVersion }}
          draft: false
          prerelease: false
